import os
import shodan
import requests
import random
import argparse


SHODAN_API_KEY = os.getenv('SHODAN_API_KEY')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

if not SHODAN_API_KEY or not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
    print("Erro: Por favor, defina as variáveis de ambiente SHODAN_API_KEY, TELEGRAM_BOT_TOKEN e TELEGRAM_CHAT_ID.")
    exit()

api = shodan.Shodan(SHODAN_API_KEY)

dorks = [
    'app="HIKVISION-综合安防管理平台"',
    '"AppleHttpServer"',
    '"AutobahnPython"',
    'basic realm="Kettle"',
    'Bullwark',
    'cassandra',
    'Chromecast',
    '"ClickShareSession"',
    '/config/log_off_page.htm',
    '"connection: upgrade"',
    '"cowboy"',
    'cpe:"cpe:2.3:a:apache:cassandra"',
    'cpe:"cpe:2.3:a:backdropcms:backdrop"',
    'cpe:"cpe:2.3:a:bolt:bolt"',
    'cpe:"cpe:2.3:a:cisco:sd-wan"',
    'cpe:"cpe:2.3:a:ckeditor:ckeditor"',
    'cpe:"cpe:2.3:a:cmsimple:cmsimple"',
    'cpe:"cpe:2.3:a:djangoproject:django"',
    'cpe:"cpe:2.3:a:eclipse:jetty"',
    'cpe:"cpe:2.3:a:embedthis:appweb"',
    'cpe:"cpe:2.3:a:embedthis:goahead"',
    'cpe:"cpe:2.3:a:exim:exim"',
    'cpe:"cpe:2.3:a:gitlist:gitlist"',
    'cpe:"cpe:2.3:a:google:web_server"',
    'cpe:"cpe:2.3:a:jfrog:artifactory"',
    'cpe:"cpe:2.3:a:kentico:kentico"',
    'cpe:"cpe:2.3:a:koha:koha"',
    'cpe:"cpe:2.3:a:konghq:docker-kong"',
    'cpe:"cpe:2.3:a:laurent_destailleur:awstats"',
    'cpe:"cpe:2.3:a:lighttpd:lighttpd"',
    'cpe:"cpe:2.3:a:microsoft:internet_information_server"',
    'cpe:"cpe:2.3:a:modx:modx_revolution"',
    'cpe:"cpe:2.3:a:nodebb:nodebb"',
    'cpe:"cpe:2.3:a:nodejs:node.js"',
    'cpe:"cpe:2.3:a:oracle:glassfish_server"',
    'cpe:"cpe:2.3:a:oracle:iplanet_web_server"',
    'cpe:"cpe:2.3:a:php:php"',
    'cpe:"cpe:2.3:a:prestashop:prestashop"',
    'cpe:"cpe:2.3:a:proftpd:proftpd"',
    'cpe:"cpe:2.3:a:public_knowledge_project:open_journal_systems"',
    'cpe:"cpe:2.3:a:pulsesecure:pulse_connect_secure"',
    'cpe:"cpe:2.3:a:rubyonrails:rails"',
    'cpe:"cpe:2.3:a:sensiolabs:symfony"',
    'cpe:"cpe:2.3:a:typo3:typo3"',
    'cpe:"cpe:2.3:a:vmware:rabbitmq"',
    'cpe:"cpe:2.3:a:webedition:webedition_cms"',
    'cpe:"cpe:2.3:a:zend:zend_server"',
    'cpe:"cpe:2.3:h:zte:f460"',
    'cpe:"cpe:2.3:o:canonical:ubuntu_linux"',
    'cpe:"cpe:2.3:o:fedoraproject:fedora"',
    'cpe:"cpe:2.3:o:microsoft:windows"',
    'DIR-845L',
    'eBridge_JSessionid',
    'ecology_JSessionid',
    'elastic indices',
    '"ElasticSearch"',
    'ESMTP',
    '/geoserver/',
    'Graylog',
    'hash:1357418825',
    'html:"access_tokens.db"',
    'html:"ACE 4710 Device Manager"',
    'html:"ActiveCollab Installer"',
    'html:"Administration - Installation - MantisBT"',
    'html:"Satis"',
    'html:"Akeeba Backup"',
    'html:"Amazon EC2 Status"',
    'html:"anonymous-cli-metrics.json"',
    'html:"anyproxy"',
    'html:"Apdisk"',
    'html:"appveyor.yml"',
    'html:"aquatronica"',
    'html:"Argo CD"',
    'html:"atlassian-connect.json"',
    'html:"auth.json"',
    'html:"authorization token is empty"',
    'html:"Avaya Aura"',
    'html:"AVideo"',
    'html:"AWS EC2 Auto Scaling Lab"',
    'html:"azure-pipelines.yml"',
    'html:"babel.config.js"',
    'html:"behat.yml"',
    'html:"BeyondTrust"',
    'html:"BIG-IP APM"',
    'html:"BIG-IP Configuration Utility"',
    'html:"bitbucket-pipelines.yml"',
    'html:"/bitrix/"',
    'html:"blazor.boot.json"',
    'html:"Blesta installer"',
    'html:"buildAssetsDir" "nuxt"',
    'html:"Calibre"',
    'html:"Cargo.lock"',
    'html:"Cargo.toml"',
    'html:"CasaOS"',
    'html:"Cassia Bluetooth Gateway Management Platform"',
    'html:"/certenroll"',
    'html:"Change Detection"',
    'html:"Cisco Expressway"',
    'html:"cisco firepower management"',
    'html:"Cisco Unity Connection"',
    'html:"/citrix/xenapp"',
    'html:"ckan 2.8.2" || html:"ckan 2.3"',
    'html:"cloud-config.yml"',
    'html:"CMS Made Simple Install/Upgrade"',
    'html:"codeception.yml"',
    'html:"CodeMeter"',
    'html:"config.rb"',
    'html:"config.ru"',
    'html:\'content="eArcu\'',
    'html:"ContentPanel SetupWizard"',
    'html:"contexts known to this"',
    'html:"Coolify" html:"register"',
    'html:"Couchbase Sync Gateway"',
    'html:"Cox Business"',
    'html:"credentials.db"',
    'html:"Crontab UI"',
    'html:"CrushFTP"',
    'html:"DashRenderer"',
    'html:"Dataease"',
    'html:"data-xwiki-reference"',
    'html="Decision Center Enterprise console"',
    'html:"Decision Center Enterprise console"',
    'html:"DefectDojo Logo"',
    'html:"def_wirelesspassword"',
    'html:"Dell OpenManage Switch Administrator"',
    'html:\'html:"desktop.ini"\'',
    'html:"DSR-250"',
    'html:"DXR.axd"',
    'html:"Easy Installer by ViserLab"',
    'html:"editorconfig"',
    'html:"EJBCA Enterprise Cloud Configuration Wizard"',
    'html:"engage - Portail soignant"',
    'html:"epihash"',
    'html:"eShop Installer"',
    'html:"ETL3100"',
    'html:"FacturaScripts installer"',
    'html:"faradayApp"',
    'html:"Femtocell Access Point"',
    'html:"FleetCart"',
    'html:"FleetCart - Installation"',
    'html:"Forgejo"',
    'html:"FortiPortal"',
    'html:"F-Secure Policy Manager"',
    'html:ftpconfig',
    'html:"ganglia_form.submit()"',
    'html:"Generated by The Webalizer"',
    'html:"GeniusOcean Installer"',
    'html:"gitlab-ci.yml"',
    'html:"git web interface version"',
    'html:"go.mod"',
    'html:"__gradio_mode__"',
    'html:"Guardfile"',
    'html:"HAL Management Console"',
    'html:"hgignore"',
    'html:"Home - CUPS"',
    'html:"HomeWorks Illumination Web Keypad"',
    'html:"Honeywell Building Control"',
    'html:"human.aspx"',
    'html:"ibmdojo"',
    'html:"iClock Automatic"',
    'html:"IDP Skills Installer"',
    'html:"imgproxy"',
    'html:"Installation" html:"itop"',
    'html:"Installation Panel"',
    'html:"Installer - GROWI"',
    'html:"Install Flarum"',
    'html:"Install - StackPosts"',
    'html:"Install the script - JustFans"',
    'html:"instance_metadata"',
    'html:"Invicti Enterprise - Installation Wizard"',
    'html:"Invoice Ninja Setup"',
    'html:"JBossWS"',
    'html:"JK Status Manager"',
    'html:"jsconfig.json"',
    'html:"jwks.json"',
    'html:"karma.conf.js"',
    'html:"LANCOM Systems GmbH"',
    'html:"Laragon" html:"phpinfo"',
    'html:"lesshst"',
    'html:"LibreNMS Install"',
    'html:"Limesurvey Installer"',
    'html:"LMSZAI - Learning Management System"',
    'html:"LoadMaster"',
    'html:"Locklizard Web Viewer"',
    'html:"Login - Jorani"',
    'html:"Login - Netflow Analyzer"',
    'html:"Login | Splunk"',
    'html:"logstash"',
    'html:"Lucee"',
    'html:"Lychee-installer"',
    'html:"Magento Installation"',
    'html:"Magnolia is a registered trademark"',
    'html:mailmap',
    'html:"manifest.json"',
    'html:"Mautic Installation"',
    'html:"mempool-space" || title:"Signet Explorer"',
    'html:"Mercurial repositories index"',
    'html:"mongod"',
    'html:"mooSocial Installation"',
    'html:"mysql_history"',
    'html:"/_next/static"',
    'html:"NGINX+ Dashboard"',
    'html:"nginxWebUI"',
    'html:"ng-version="',
    'html:"nopCommerce Installation"',
    'html:"npm-debug.log"',
    'html:"npm-shrinkwrap.json"',
    'html:"Ocp-Apim-Subscription-Key"',
    'html:"omniapp"',
    'html:"Open Journal Systems"',
    'html:"Orbit Telephone System"',
    'html:"Orchard Setup - Get Started"',
    'html:"osCommerce"',
    'html:"packages.config"',
    'html:"parameters.yml"',
    'html:"PDI Intellifuel"',
    'html:"phinx.yml"',
    'html:"php_cs.cache"',
    'html:"phpcs.xml"',
    'html:"phpdebugbar"',
    'html:"/phpgedview.db"',
    'html:"phpipam installation wizard"',
    'html:"phpLDAPadmin"',
    'html:"phplist"',
    'html:"phpspec.yml"',
    'html:"phpstan.neon"',
    'html:"phpSysInfo"',
    'html:"pipeline.yaml"',
    'html:"Pipfile"',
    'html:"Piwigo" html:"- Installation"',
    'html:"Plausible"',
    'html:"pnpm-lock.yaml"',
    'html:"polyfill.io"',
    'html:"Portal Setup"',
    'html:"PowerChute Network Shutdown"',
    'html:"Powered by Gitea"',
    'html:"PowerShell Universal"',
    'html:"private gpt"',
    'html:"Procfile"',
    'html:"ProfitTrailer Setup"',
    'html:"ProjectSend setup"',
    'html:"protractor.conf.js"',
    'html:"Provide a link that opens Word"',
    'html:"psalm.xml"',
    'html:"pubspec.yaml"',
    'html:"pyload"',
    'html:"pypiserver"',
    'html:"pyproject.toml"',
    'html:"python_gc_objects_collected_total"',
    'html:"QuickCMS Installation"',
    'html:"QVidium Management"',
    'html:"radarr"',
    'html:"RaidenMAILD"',
    'html:"Rakefile"',
    'html:"readarr"',
    'html:"README.MD"',
    'html:"Redash Initial Setup"',
    'html:"redis.conf"',
    'html:"redis.exceptions.ConnectionError"',
    'html:"request-baskets"',
    'html:"rollup.config.js"',
    'html:"rubocop.yml"',
    'html:"SABnzbd Quick-Start Wizard"',
    'html:"Salia PLCC"',
    'html:"SAP"',
    'html:"sass-lint.yml"',
    'html:"scrutinizer.yml"',
    'html:"SDT-CW3B1"',
    'html:"searchreplacedb2.php"',
    'html:\'Select a frequency for snapshot retention\'',
    'html:"sendgrid.env"',
    'html:"Sentinel License Monitor"',
    'html:"server_databases.php"',
    'html:"Serv-U"',
    'html:settings.py',
    'html:"Setup GLPI"',
    'html:"Setup - jfa-go"',
    'html:"sftp.json"',
    'html:"shopping cart program by zen cart"',
    'html:"Sitecore"',
    'html:"Snipe-IT Setup"',
    'html:"sonarr"',
    'html:"Sorry, the requested URL"',
    'html:"stackposts"',
    'html:"Struts Problem Report"',
    'html:"Symmetricom SyncServer"',
    'html:"thisIDRACText"',
    'html:"Tiny File Manager"',
    'html:"<title>Admin Console</title>"',
    'html:\'title="Lucy\'',
    'html:"<title>prowlarr</title>"',
    'html:"<title>Stash</title>"',
    'html:"tox.ini"',
    'html:"Traccar"',
    'html:"travis.yml"',
    'html:"Trilium Notes"',
    'html:"TurboMeeting"',
    'html:"Ubersmith Setup"',
    'html:"UEditor"',
    'html:"UPS Network Management Card 4"',
    'html:"UrBackup - Keeps your data safe"',
    'html:"utnserver Control Center"',
    'html:"UVDesk Helpdesk Community Edition - Installation Wizard"',
    'html:"uwsgi.ini"',
    'html:"Vagrantfile"',
    'html:"Versa Networks"',
    'html:"Viminfo"',
    'html:"VinChin"',
    'html:"Virtual SmartZone"',
    'html:"vite.config.js"',
    'html:"vmw_nsx_logo-black-triangle-500w.png"',
    'html:"voyager-assets"',
    'html:"/vsaas/v2/static/"',
    'html:"webpack.config.js"',
    'html:"webpackJsonpzipkin-lens"',
    'html:"webpack.mix.js"',
    'html:"welcome.cgi?p=logo"',
    'html:"Welcome to CakePHP"',
    'html:"Welcome to Espocrm"',
    'html:"Welcome to Express"',
    'html:"Welcome to Nginx"',
    'html:"Welcome to Openfire Setup"',
    'html:"Welcome to Progress Application Server for OpenEdge"',
    'html:"Welcome to the Ruckus"',
    'html:"Welcome to Vtiger CRM"',
    'html:"Werkzeug powered traceback interpreter"',
    'html:".wget-hsts"',
    'html:".wgetrc"',
    'html:"WhatsUp Gold"',
    'html:"Whisparr"',
    'html:"Whitelabel Error Page"',
    'html:"window.nps"',
    'html:"wpad.dat"',
    'html:"wp-cli.yml"',
    'html:"XBackBone Installer"',
    'html:XploitSPY',
    'html:"yii\base\ErrorException"',
    'html:"Zebra Technologies"',
    'html:"ZzzCMS"',
    'HTTP/1.0 401 Please Authenticate\r\nWWW-Authenticate: Basic realm="Please Login"',
    'http.component:"Adobe ColdFusion"',
    'http.component:"Adobe Experience Manager"',
    'http.component:"atlassian confluence"',
    'http.component:"Atlassian Confluence"',
    'http.component:"atlassian jira"',
    'http.component:"Atlassian Jira"',
    'http.component:"Bitbucket"',
    'http.component:"BitBucket"',
    'http.component:"drupal"',
    'http.component:"Drupal"',
    'http.component:"Dynamicweb"',
    'http.component:"ghost"',
    'http.component:"Joomla"',
    'http.component:"magento"',
    'http.component:"Magento"',
    'http.component:"October CMS"',
    'http.component:"prestashop"',
    'http.component:"PrestaShop"',
    'http.component:"RoundCube"',
    'http.component:"Subrion"',
    'http.component:"TeamCity"',
    'http.component:"TYPO3"',
    'http.component:"vBulletin"',
    'http.component:zk http.title:"Server Backup Manager"',
    'http.favicon.hash:-1005691603',
    'http.favicon.hash:1011076161',
    'http.favicon.hash:-1013024216',
    'http.favicon.hash:1017650009',
    'http.favicon.hash:1052926265',
    'http.favicon.hash:-1074357885',
    'http.favicon.hash:1090061843',
    'http.favicon.hash:1099097618',
    'http.favicon.hash:1099370896',
    'http.favicon.hash:-1101206929',
    'http.favicon.hash:-1117549627',
    'http.favicon.hash:-1127895693',
    'http.favicon.hash:115295460',
    'http.favicon.hash:116323821',
    'http.favicon.hash:11794165',
    'http.favicon.hash:1198579728',
    'http.favicon.hash:1199592666',
    'http.favicon.hash:-1215318992',
    'http.favicon.hash:-121681558',
    'http.favicon.hash:-1247684400',
    'http.favicon.hash:1249285083',
    'http.favicon.hash:-1250474341',
    'http.favicon.hash:-1261322577',
    'http.favicon.hash:1262005940',
    'http.favicon.hash:-1264095219',
    'http.favicon.hash:-1292923998,-1166125415',
    'http.favicon.hash:-1295577382',
    'http.favicon.hash:-1298131932',
    'http.favicon.hash:-130447705',
    'http.favicon.hash:1337147129',
    'http.favicon.hash:-1341442175',
    'http.favicon.hash:-1343712810',
    'http.favicon.hash:-1350437236',
    'http.favicon.hash:1354079303',
    'http.favicon.hash:-1373456171',
    'http.favicon.hash:-1379982221',
    'http.favicon.hash:1380908726',
    'http.favicon.hash:-1381126564',
    'http.favicon.hash:-1383463717',
    'http.favicon.hash:1398055326',
    'http.favicon.hash:1410071322',
    'http.favicon.hash:-1414548363',
    'http.favicon.hash:-1416464161',
    'http.favicon.hash:-1465760059',
    'http.favicon.hash:-1478287554',
    'http.favicon.hash:-1495233116',
    'http.favicon.hash:-1499940355',
    'http.favicon.hash:-1529860313',
    'http.favicon.hash:1540720428',
    'http.favicon.hash:-1548359600',
    'http.favicon.hash:1550906681',
    'http.favicon.hash:1552322396',
    'http.favicon.hash:-1575154882',
    'http.favicon.hash:-1595726841',
    'http.favicon.hash:1604363273',
    'http.favicon.hash:1606029165',
    'http.favicon.hash:-1606065523',
    'http.favicon.hash:-1649949475',
    'http.favicon.hash:1653394551',
    'http.favicon.hash:-1653412201',
    'http.favicon.hash:"-165631681"',
    'http.favicon.hash:-1663319756',
    'http.favicon.hash:-1680052984',
    'http.favicon.hash:1691956220',
    'http.favicon.hash:1693580324',
    'http.favicon.hash:-1706783005',
    'http.favicon.hash:1749354953',
    'http.favicon.hash:176427349',
    'http.favicon.hash:1781653957',
    'http.favicon.hash:-1797138069',
    'http.favicon.hash:1817615343',
    'http.favicon.hash:1828614783',
    'http.favicon.hash:"-1830859634"',
    'http.favicon.hash:-186961397',
    'http.favicon.hash:-1893514038',
    'http.favicon.hash:-1898583197',
    'http.favicon.hash:1903390397',
    'http.favicon.hash:-1950415971',
    'http.favicon.hash:1952289652',
    'http.favicon.hash:-1961736892',
    'http.favicon.hash:-1970367401',
    'http.favicon.hash:-2017596142',
    'http.favicon.hash:-2017604252',
    'http.favicon.hash:2019488876',
    'http.favicon.hash:-2028554187',
    'http.favicon.hash:-2032163853',
    'http.favicon.hash:-2051052918',
    'http.favicon.hash:2056442365',
    'http.favicon.hash:206985584',
    'http.favicon.hash:-2073748627 || http.favicon.hash:-1721140132',
    'http.favicon.hash:2099342476',
    'http.favicon.hash:2104916232',
    'http.favicon.hash:"-211006074"',
    'http.favicon.hash:-211006074',
    'http.favicon.hash:-2115208104',
    'http.favicon.hash:2124459909',
    'http.favicon.hash:213144638',
    'http.favicon.hash:2134367771',
    'http.favicon.hash:-2144699833',
    'http.favicon.hash:-219625874',
    'http.favicon.hash:-234335289',
    'http.favicon.hash:24048806',
    'http.favicon.hash:-244067125',
    'http.favicon.hash:262502857',
    'http.favicon.hash:-266008933',
    'http.favicon.hash:-283003760',
    'http.favicon.hash:-286484075',
    'http.favicon.hash:305412257',
    'http.favicon.hash:321591353',
    'http.favicon.hash:-347188002',
    'http.favicon.hash:-374133142',
    'http.favicon.hash:-399298961',
    'http.favicon.hash:407286339',
    'http.favicon.hash:-417785140',
    'http.favicon.hash:-418614327',
    'http.favicon.hash:419828698',
    'http.favicon.hash:431627549',
    'http.favicon.hash:-43504595',
    'http.favicon.hash:439373620',
    'http.favicon.hash:440258421',
    'http.favicon.hash:-440644339',
    'http.favicon.hash:450899026',
    'http.favicon.hash:464587962',
    'http.favicon.hash:487145192',
    'http.favicon.hash:-50306417',
    'http.favicon.hash:523757057',
    'http.favicon.hash:538583492',
    'http.favicon.hash:540706145',
    'http.favicon.hash:557327884',
    'http.favicon.hash:-578216669',
    'http.favicon.hash:587330928',
    'http.favicon.hash:-594722214',
    'http.favicon.hash:598296063',
    'http.favicon.hash:-608690655',
    'http.favicon.hash:-629968763',
    'http.favicon.hash:-633512412',
    'http.favicon.hash:635899646',
    'http.favicon.hash:"-646322113"',
    'http.favicon.hash:-655683626',
    'http.favicon.hash:657337228',
    'http.favicon.hash:662709064',
    'http.favicon.hash:"-670975485"',
    'http.favicon.hash:-697231354',
    'http.favicon.hash:698624197',
    'http.favicon.hash:"702863115"',
    'http.favicon.hash:702863115clear',
    'http.favicon.hash:733091897',
    'http.favicon.hash:739801466',
    'http.favicon.hash:-741491222',
    'http.favicon.hash:-749942143',
    'http.favicon.hash:751911084',
    'http.favicon.hash:762074255',
    'http.favicon.hash:781922099',
    'http.favicon.hash:786533217',
    'http.favicon.hash:-800060828',
    'http.favicon.hash:-800551065',
    'http.favicon.hash:-81573405',
    'http.favicon.hash:816588900',
    'http.favicon.hash:824580113',
    'http.favicon.hash:-82958153',
    'http.favicon.hash:-831756631',
    'http.favicon.hash:"-839356603"',
    'http.favicon.hash:-850502287',
    'http.favicon.hash:855432563',
    'http.favicon.hash:868509217',
    'http.favicon.hash:"871154672"',
    'http.favicon.hash:874152924',
    'http.favicon.hash:876876147',
    'http.favicon.hash:889652940',
    'http.favicon.hash:-902890504',
    'http.favicon.hash:-916902413',
    'http.favicon.hash:-919788577',
    'http.favicon.hash:932345713',
    'http.favicon.hash:933976300',
    'http.favicon.hash:942678640',
    'http.favicon.hash:957255151',
    'http.favicon.hash:965982073',
    'http.favicon.hash:967636089',
    'http.favicon.hash:969374472',
    'http.favicon.hash:-976853304',
    'http.favicon.hash:-977323269',
    'http.favicon.hash:981081715',
    'http.favicon.hash:983734701',
    'http.favicon.hash:988422585',
    'http.favicon.hash:989289239',
    'http.favicon.hash:999357577',
    'http.html:"4DACTION/"',
    'http.html:"74cms"',
    'http.html:"academy lms"',
    'http.html:"Ampache Update"',
    'http.html:"Apache Airflow"',
    'http.html:"Apache Axis"',
    'http.html:"Apache Cocoon"',
    'http.html:"Apache OFBiz"',
    'http.html:"Apache Solr"',
    'http.html:"apollo-adminservice"',
    'http.html:"app.2fe6356cdd1ddd0eb8d6317d1a48d379.css"',
    'http.html:"artica"',
    'http.html:".asmx?WSDL"',
    'http.html:"Audiocodes"',
    'http.html:"BeyondInsight"',
    'http.html:"BeyondTrust Privileged Remote Access Login"',
    'http.html:"bigant"',
    'http.html:"BigAnt Admin"',
    'http.html:"/bitrix/"',
    'http.html:"blogengine.net"',
    'http.html:"BMC Remedy"',
    'http.html:"Camunda Welcome"',
    'http.html:"car rental management system"',
    'http.html:"Car Rental Management System"',
    'http.html:"/CasaOS-UI/public/index.html"',
    'http.html:"CCM - Authentication Failure"',
    'http.html:"Check Point Mobile"',
    'http.html:"chronoslogin.js"',
    'http.html:"CMS Quilium"',
    'http.html:"Command API Explorer"',
    'http.html:\'content="Redmine\'',
    'http.html:\'content="Smartstore\'',
    'http.html:"corebos"',
    'http.html:"crushftp"',
    'http.html:"CS141"',
    'http.html:"Cvent Inc"',
    'http.html:"CxSASTManagerUri"',
    'http.html:"DedeCms"',
    'http.html:"Delta Controls ORCAview"',
    'http.html:"Develocity Build Cache Node"',
    'http.html:"DLP system"',
    'http.html:"/dokuwiki/"',
    'http.html:"dotnetcms"',
    'http.html:"dzzoffice"',
    'http.html:"E-Mobile"',
    'http.html:"EmpireCMS"',
    'http.html:"ESP Easy Mega"',
    'http.html:"eZ Publish"',
    'http.html:"Flatpress"',
    'http.html:"Fuji Xerox Co., Ltd"',
    'http.html:"Get_Verify_Info"',
    'http.html:"glpi"',
    'http.html:"Gnuboard"',
    'http.html:"gnuboard5"',
    'http.html:"GoAnywhere Managed File Transfer"',
    'http.html:"Gradle Enterprise Build Cache Node"',
    'http.html:"H3C-SecPath-运维审计系统"',
    'http.html_hash:1015055567',
    'http.html_hash:1076109428',
    'http.html_hash:-14029177',
    'http.html_hash:-1957161625',
    'http.html_hash:510586239',
    'http.html:"HG532e"',
    'http.html:"hospital management system"',
    'http.html:"Hospital Management System"',
    'http.html:\'Hugo\'',
    'http.html:"i3geo"',
    'http.html:"IBM WebSphere Portal"',
    'http.html:"import-xml-feed"',
    'http.html:"index.createOpenPad"',
    'http.html:"Interactsh Server"',
    'http.html:"IPdiva"',
    'http.html:"iSpy"',
    'http.html:"JamF"',
    'http.html:"Jamf Pro Setup"',
    'http.html:"Jellyfin"',
    'http.html:"JHipster"',
    'http.html:"kavita"',
    'http.html:"LANDESK(R)"',
    'http.html:"Laravel FileManager"',
    'http.html:livezilla',
    'http.html:"Login (Virtual Traffic Manager"',
    'http.html:"lookerVersion"',
    'http.html:"magnusbilling"',
    'http.html:"mailhog"',
    'http.html:"/main/login.lua?pageid="',
    'http.html:"metersphere"',
    'http.html:"MiCollab End User Portal"',
    'http.html:"Micro Focus Application Lifecycle Management"',
    'http.html:"Micro Focus iPrint Appliance"',
    'http.html:"Mirantis Kubernetes Engine"',
    'http.html:"MobileIron"',
    'http.html:"moodle"',
    'http.html:"multipart/form-data" html:"file"',
    'http.html:"myLittleAdmin"',
    'http.html:"myLittleBackup"',
    'http.html:"NeoboxUI"',
    'http.html:"Network Utility"',
    'http.html:"Nexus Repository Manager"',
    'http.html:\'ng-app="syncthing"\'',
    'http.html:"Nordex Control"',
    'http.html:"Omnia MPX"',
    'http.html:"OpenCTI"',
    'http.html:"OpenEMR"',
    'http.html:"opennebula"',
    'http.html:"Oracle HTTP Server"',
    'http.html:"Oracle UIX"',
    'http.html:"outsystems"',
    'http.html:"owncloud"',
    'http.html:"PbootCMS"',
    'http.html:"phpMiniAdmin"',
    'http.html:"phpMyAdmin"',
    'http.html:"phpmyfaq"',
    'http.html:/plugins/royal-elementor-addons/',
    'http.html:"power by dedecms" || title:"dedecms"',
    'http.html:"Powerd by AppCMS"',
    'http.html:"powered by CATALOGcreator"',
    'http.html:"powerjob"',
    'http.html:"processwire"',
    'http.html:provided by projectsend',
    'http.html:"/redfish/v1"',
    'http.html:"redhat" "Satellite"',
    'http.html:"r-seenet"',
    'http.html:rt_title',
    'http.html:"SAP Analytics Cloud"',
    'http.html:"seafile"',
    'http.html:"Semaphore</title>"',
    'http.html:"sharecenter"',
    'http.html:"SLIMS"',
    'http.html:"SolarView Compact"',
    'http.html:"soplanning"',
    'http.html:"SOUND4"',
    'http.html:"study any topic, anytime"',
    'http.html:"sucuri firewall"',
    'http.html:"symfony Profiler"',
    'http.html:"sympa"',
    'http.html:"teampass"',
    'http.html:"Telerik Report Server"',
    'http.html:"thruk"',
    'http.html:"Thruk"',
    'http.html:"TIBCO BusinessConnect"',
    'http.html:"tiki wiki"',
    'http.html:"TLR-2005KSH"',
    'http.html:"totemomail" inurl:responsiveui',
    'http.html:"Umbraco"',
    'http.html:"Vertex Tax Installer"',
    'http.html:"VMG1312-B10D"',
    'http.html:"VMware Horizon"',
    'http.html:"VSG1432-B101"',
    'http.html:"wavlink"',
    'http.html:"Wavlink"',
    'http.html:"WebADM"',
    'http.html:"Webasyst Installer"',
    'http.html:"WebCenter"',
    'http.html:"Webp"',
    'http.html:"webshell4"',
    'http.html:"Welcome to MapProxy"',
    'http.html:/wp-content/plugins/adsense-plugin/',
    'http.html:wp-content/plugins/ap-pricing-tables-lite',
    'http.html:/wp-content/plugins/autoptimize',
    'http.html:/wp-content/plugins/backup-backup/',
    'http.html:/wp-content/plugins/bws-google-analytics/',
    'http.html:/wp-content/plugins/bws-google-maps/',
    'http.html:/wp-content/plugins/bws-linkedin/',
    'http.html:/wp-content/plugins/bws-pinterest/',
    'http.html:/wp-content/plugins/bws-smtp/',
    'http.html:/wp-content/plugins/bws-testimonials/',
    'http.html:/wp-content/plugins/chaty/',
    'http.html:/wp-content/plugins/cmp-coming-soon-maintenance/',
    'http.html:/wp-content/plugins/companion-sitemap-generator/',
    'http.html:/wp-content/plugins/contact-form-multi/',
    'http.html:/wp-content/plugins/contact-form-plugin/',
    'http.html:/wp-content/plugins/contact-form-to-db/',
    'http.html:/wp-content/plugins/contest-gallery/',
    'http.html:/wp-content/plugins/controlled-admin-access/',
    'http.html:/wp-content/plugins/cryptocurrency-widgets-pack/',
    'http.html:/wp-content/plugins/custom-admin-page/',
    'http.html:/wp-content/plugins/custom-facebook-feed/',
    'http.html:/wp-content/plugins/custom-search-plugin/',
    'http.html:/wp-content/plugins/defender-security/',
    'http.html:/wp-content/plugins/ditty-news-ticker/',
    'http.html:/wp-content/plugins/download-monitor/',
    'http.html:/wp-content/plugins/error-log-viewer/',
    'http.html:/wp-content/plugins/essential-blocks/',
    'http.html:/wp-content/plugins/extensive-vc-addon/',
    'http.html:/wp-content/plugins/foogallery/',
    'http.html:/wp-content/plugins/forminator',
    'http.html:/wp-content/plugins/g-auto-hyperlink/',
    'http.html:/wp-content/plugins/gift-voucher/',
    'http.html:/wp-content/plugins/gtranslate',
    'http.html:/wp-content/plugins/htaccess/',
    'http.html:/wp-content/plugins/learnpress',
    'http.html:/wp-content/plugins/login-as-customer-or-user',
    'http.html:wp-content/plugins/media-library-assistant',
    'http.html:/wp-content/plugins/motopress-hotel-booking',
    'http.html:/wp-content/plugins/mstore-api/',
    'http.html:/wp-content/plugins/newsletter/',
    'http.html:/wp-content/plugins/nex-forms-express-wp-form-builder/',
    'http.html:/wp-content/plugins/ninja-forms/',
    'http.html:/wp-content/plugins/pagination/',
    'http.html:/wp-content/plugins/paid-memberships-pro/',
    'http.html:/wp-content/plugins/pdf-generator-for-wp',
    'http.html:/wp-content/plugins/pdf-print/',
    'http.html:/wp-content/plugins/photoblocks-grid-gallery/',
    'http.html:/wp-content/plugins/photo-gallery',
    'http.html:/wp-content/plugins/polls-widget/',
    'http.html:/wp-content/plugins/popup-builder/',
    'http.html:/wp-content/plugins/popup-by-supsystic',
    'http.html:/wp-content/plugins/popup-maker/',
    'http.html:/wp-content/plugins/post-smtp',
    'http.html:/wp-content/plugins/prismatic',
    'http.html:/wp-content/plugins/promobar/',
    'http.html:/wp-content/plugins/qt-kentharadio',
    'http.html:/wp-content/plugins/quick-event-manager',
    'http.html:/wp-content/plugins/rating-bws/',
    'http.html:/wp-content/plugins/realty/',
    'http.html:/wp-content/plugins/registrations-for-the-events-calendar/',
    'http.html:/wp-content/plugins/searchwp-live-ajax-search/',
    'http.html:/wp-content/plugins/sender/',
    'http.html:/wp-content/plugins/sfwd-lms',
    'http.html:/wp-content/plugins/shortpixel-adaptive-images/',
    'http.html:/wp-content/plugins/show-all-comments-in-one-page',
    'http.html:/wp-content/plugins/site-offline/',
    'http.html:/wp-content/plugins/social-buttons-pack/',
    'http.html:/wp-content/plugins/social-login-bws/',
    'http.html:/wp-content/plugins/stock-ticker/',
    'http.html:/wp-content/plugins/subscriber/',
    'http.html:/wp-content/plugins/super-socializer/',
    'http.html:/wp-content/plugins/tutor/',
    'http.html:/wp-content/plugins/twitter-plugin/',
    'http.html:/wp-content/plugins/ubigeo-peru/',
    'http.html:/wp-content/plugins/ultimate-member',
    'http.html:/wp-content/plugins/updater/',
    'http.html:/wp-content/plugins/user-meta/',
    'http.html:/wp-content/plugins/user-role/',
    'http.html:/wp-content/plugins/video-list-manager/',
    'http.html:/wp-content/plugins/visitors-online/',
    'http.html:/wp-content/plugins/wc-multivendor-marketplace',
    'http.html:/wp-content/plugins/woocommerce-payments',
    'http.html:/wp-content/plugins/wordpress-toolbar/',
    'http.html:/wp-content/plugins/wp-fastest-cache/',
    'http.html:/wp-content/plugins/wp-helper-lite',
    'http.html:/wp-content/plugins/wp-simple-firewall',
    'http.html:/wp-content/plugins/wp-statistics/',
    'http.html:/wp-content/plugins/wp-user/',
    'http.html:/wp-content/plugins/zendesk-help-center/',
    'http.html:/wp-content/themes/newspaper',
    'http.html:/wp-content/themes/noo-jobmonster',
    'http.html:"wp-stats-manager"',
    'http.html:"Wuzhicms"',
    'http.html:"/xibosignage/xibo-cms"',
    'http.html:"yeswiki"',
    'http.html:"Z-BlogPHP"',
    'http.html:"zm - login"',
    'http.html:"ZTE Corporation"',
    'http.html:"心上无垢，林间有风"',
    'http.securitytxt:contact http.status:200',
    'http.title:"3CX Phone System Management Console"',
    'http.title:"Accueil WAMPSERVER"',
    'http.title:"Acrolinx Dashboard"',
    'http.title:"Admin | Employee\'s Payroll Management System"',
    'http.title:adminer',
    'http.title:"AdmiralCloud"',
    'http.title:"Adobe Media Server"',
    'http.title:"Aerohive NetConfig UI"',
    'http.title:"AirCube Dashboard"',
    'http.title:"AirNotifier"',
    'http.title:"Alertmanager"',
    'http.title:"AlienVault USM"',
    'http.title:"Amazon Cognito Developer Authentication Sample"',
    'http.title:"Ampache -- Debug Page"',
    'http.title:"Android Debug Database"',
    'http.title:"Apache2 Debian Default Page:"',
    'http.title:"Apache2 Ubuntu Default Page"',
    'http.title:"apache apisix dashboard"',
    'http.title:"Apache CloudStack"',
    'http.title:"Apache+Default","Apache+HTTP+Server+Test","Apache2+It+works"',
    'http.title:"Apache HTTP Server Test Page powered by CentOS"',
    'http.title:"apache streampipes"',
    'http.title:"apex it help desk"',
    'http.title:"appsmith"',
    'http.title:"Aptus Login"',
    'http.title:"Aqua Enterprise" || http.title:"Aqua Cloud Native Security Platform"',
    'http.title:"Argo CD"',
    'http.title:"avantfax - login"',
    'http.title:"aviatrix cloud controller"',
    'http.title:"AVideo"',
    'http.title:"Axel"',
    'http.title:"Axigen WebAdmin"',
    'http.title:"Axigen WebMail"',
    'http.title:"Axway API Manager Login"',
    'http.title:"Axyom Network Manager"',
    'http.title:"Azkaban Web Client"',
    'http.title:"Bagisto Installer"',
    'http.title:"Bamboo"',
    'http.title:"BigBlueButton"',
    'http.title:"BigFix"',
    'http.title:"big-ip®-+redirect" +"server"',
    'http.title:"BioTime"',
    'http.title:"Black Duck"',
    'http.title:"Blue Iris Login"',
    'http.title:"BMC Remedy Single Sign-On domain data entry"',
    'http.title:"BMC Software"',
    'http.title:"browserless debugger"',
    'http.title:"Caton Network Manager System"',
    'http.title:"Celebrus"',
    'http.title:"Centreon"',
    'http.title:"Charger Management Console"',
    'http.title:"Check_MK"',
    'http.title:"Cisco Secure CN"',
    'http.title:"Cisco ServiceGrid"',
    'http.title:"Cisco Systems Login"',
    'http.title:"Cisco Telepresence"',
    'http.title:"citrix gateway"',
    'http.title:"ClarityVista"',
    'http.title:"CleanWeb"',
    'http.title:"Cloudphysician RADAR"',
    'http.title:"Cluster Overview - Trino"',
    'http.title:"C-more -- the best HMI presented by AutomationDirect"',
    'http.title:"cobbler web interface"',
    'http.title:"Codeigniter Application Installer"',
    'http.title:"code-server login"',
    'http.title:"Codian MCU - Home page"',
    'http.title:"CompleteView Web Client"',
    'http.title:"Conductor UI", http.title:"Workflow UI"',
    'http.title:"Connection - SphinxOnline"',
    'http.title:"Content Central Login"',
    'http.title:"copyparty"',
    'http.title:"Coverity"',
    'http.title:"craftercms"',
    'http.title:"Create a pipeline - Go" html:"GoCD Version"',
    'http.title:"Creatio"',
    'http.title:"Database Error"',
    'http.title:"DataHub"',
    'http.title:"datataker"',
    'http.title:"Davantis"',
    'http.title:"Decision Center | Business Console"',
    'http.title:"Dericam"',
    'http.title:"Dgraph Ratel Dashboard"',
    'http.title:"docassemble"',
    'http.title:"Dolibarr"',
    'http.title:"DolphinScheduler"',
    'http.title:"dotcms"',
    'http.title:"Dozzle"',
    'http.title:"Easyvista"',
    'http.title:"Ekoenergetyka-Polska Sp. z o.o - CCU3 Software Update for Embedded Systems"',
    'http.title:"Elastic" || http.favicon.hash:1328449667',
    'http.title:"Elasticsearch-sql client"',
    'http.title:"emby"',
    'http.title:"emerge"',
    'http.title:"Emerson Network Power IntelliSlot Web Card"',
    'http.title:"EMQX Dashboard"',
    'http.title:"Endpoint Protector"',
    'http.title:"EnvisionGateway"',
    'http.title:"erxes"',
    'http.title:"EWM Manager"',
    'http.title:"Extreme NetConfig UI"',
    'http.title:"Falcosidekick"',
    'http.title:"FastCGI"',
    'http.title:"Flex VNF Web-UI"',
    'http.title:"flightpath"',
    'http.title:"flowchart maker"',
    'http.title:"Forcepoint Appliance"',
    'http.title:"fortimail"',
    'http.title:"FORTINET LOGIN"',
    'http.title:"fortiweb - "',
    'http.title:"fuel cms"',
    'http.title:"GeoWebServer"',
    'http.title:"gitbook"',
    'http.title:"GitHub Debug"',
    'http.title:"GitLab"',
    'http.title:"git repository browser"',
    'http.title:"GlassFish Server - Server Running"',
    'http.title:"Glowroot"',
    'http.title:"Gophish - Login"',
    'http.title:"Grandstream Device Configuration"',
    'http.title:"Graphite Browser"',
    'http.title:"Graylog Web Interface"',
    'http.title:"Gryphon"',
    'http.title:"GXD5 Pacs Connexion utilisateur"',
    'http.title:"H5S CONSOLE"',
    'http.title:"Hacked By"',
    'http.title:"Haivision Gateway"',
    'http.title:"Haivision Media Platform"',
    'http.title:"hd-network real-time monitoring system v2.0"',
    'http.title:"Heatmiser Wifi Thermostat"',
    'http.title:"HiveQueue"',
    'http.title:"Home Assistant"',
    'http.title:"Home Page - My ASP.NET Application"',
    'http.title:"HP BladeSystem"',
    'http.title:"HP Color LaserJet"',
    'http.title:"Hp Officejet pro"',
    'http.title:"HP Virtual Connect Manager"',
    'http.title:"httpbin.org"',
    'http.title:"HTTP Server Test Page powered by CentOS-WebPanel.com"',
    'http.title:"HUAWEI Home Gateway HG658d"',
    'http.title:"hybris"',
    'http.title:"IBM-HTTP-Server"',
    'http.title:"IBM iNotes Login"',
    'http.title:"IBM Security Access Manager"',
    'http.title:"Icecast Streaming Media Server"',
    'http.title:"IdentityServer v3"',
    'http.title:"IIS7"',
    'http.title:"IIS Windows Server"',
    'http.title:"ImpressPages installation wizard"',
    'http.title:"Installation - Gogs"',
    'http.title:"Installer - Easyscripts"',
    'http.title:"Intelbras"',
    'http.title:"Intelligent WAPPLES"',
    'http.title:"IoT vDME Simulator"',
    'http.title:"ispconfig"',
    'http.title:"iXBus"',
    'http.title:"J2EE"',
    'http.title:"Jaeger UI"',
    'http.title:"jeedom"',
    'http.title:"Jellyfin"',
    'http.title:"JFrog"',
    'http.title:"Jitsi Meet"',
    'http.title:"JumpServer"',
    'http.title:"Juniper Web Device Manager"',
    'http.title:"JupyterHub"',
    'http.title:"Kafka Center"',
    'http.title:"Kafka Cruise Control UI"',
    'http.title:"kavita"',
    'http.title:"Kerio Connect Client"',
    'http.title:"kibana"',
    'http.title:"kkFileView"',
    'http.title:"Kopano WebApp"',
    'http.title:"Kraken dashboard"',
    'http.title:"Kubernetes Operational View"',
    'http.title:"kubernetes web view"',
    'http.title:"lansweeper - login"',
    'http.title:"LDAP Account Manager"',
    'http.title:"Leostream"',
    'http.title:"Linksys Smart WI-FI"',
    'http.title:"LinShare"',
    'http.title:"LockSelf"',
    'http.title:"login | control webpanel"',
    'http.title:"Log in - easyJOB"',
    'http.title:"Login - Residential Gateway"',
    'http.title:"login - splunk"',
    'http.title:"Login - Splunk"',
    'http.title:"login" "x-oracle-dms-ecid" 200',
    'http.title:"Logitech Harmony Pro Installer"',
    'http.title:"Lomnido Login"',
    'http.title:"Loxone Intercom Video"',
    'http.title:"Lucee"',
    'http.title:"Maestro - LuCI"',
    'http.title:"MAG Dashboard Login"',
    'http.title:"MailWatch Login Page"',
    'http.title:"manageengine desktop central 10"',
    'http.title:"ManageEngine Password"',
    'http.title:"manageengine servicedesk plus"',
    'http.title:"mcloud-installer-web"',
    'http.title:"Meduza Stealer"',
    'http.title:"MetaView Explorer"',
    'http.title:"MeTube"',
    'http.title:"Microsoft Azure App Service - Welcome"',
    'http.title:"Microsoft Internet Information Services 8"',
    'http.title:"mikrotik routeros > administration"',
    'http.title:"mlflow"',
    'http.title:"MobiProxy"',
    'http.title:"MongoDB Ops Manager"',
    'http.title:"mongo express"',
    'http.title:"MSPControl - Sign In"',
    'http.title:"My Datacenter - Login"',
    'http.title:"Mystic Stealer"',
    'http.title:"nagios"',
    'http.title:"nagios xi"',
    'http.title:"N-central Login"',
    'http.title:"nconf"',
    'http.title:"Netris Dashboard"',
    'http.title:"NETSurveillance WEB"',
    'http.title:"NetSUS Server Login"',
    'http.title:"Nextcloud"',
    'http.title:"nginx admin manager"',
    'http.title:"Nginx Proxy Manager"',
    'http.title:"ngrok"',
    'http.title:"Normhost Backup server manager"',
    'http.title:"noVNC"',
    'http.title:"NS-ASG"',
    'http.title:"ntopng - Traffic Dashboard"',
    'http.title:"okta"',
    'http.title:"Olivetti CRF"',
    'http.title:"OneinStack"',
    'http.title:"Opcache Control Panel"',
    'http.title:"Open Game Panel"',
    'http.title:"openHAB"',
    'http.title:"openSIS"',
    'http.title:"openvpn connect"',
    'http.title:"Operations Automation Default Page"',
    'http.title:"Opinio"',
    'http.title:"opmanager plus"',
    'http.title:"opnsense"',
    'http.title:"opsview"',
    'http.title:"Oracle Application Server Containers"',
    'http.title:"oracle business intelligence sign in"',
    'http.title:"Oracle Containers for J2EE"',
    'http.title:"Oracle Database as a Service"',
    'http.title:"Oracle PeopleSoft Sign-in"',
    'http.title:"Oracle(R) Integrated Lights Out Manager"',
    'http.title:"OrangeHRM Web Installation Wizard"',
    'http.title:"OSNEXUS QuantaStor Manager"',
    'http.title:"otobo"',
    'http.title:"OurMGMT3"',
    'http.title:outlook exchange',
    'http.title:"OVPN Config Download"',
    'http.title:"PAHTool"',
    'http.title:"pandora fms"',
    'http.title:"Passbolt | Open source password manager for teams"',
    'http.title:"Payara Server - Server Running"',
    'http.title:"PendingInstallVZW - Web Page Configuration"',
    'http.title:"Pexip Connect for Web"',
    'http.title:"pfsense - login"',
    'http.title:"PGP Global Directory"',
    'http.title:"phoronix-test-suite"',
    'http.title:"PhotoPrism"',
    'http.title:"PHP Mailer"',
    'http.title:"phpMyAdmin"',
    'http.title:"PHP warning" || "Fatal error"',
    'http.title:"Plastic SCM"',
    'http.title:"Please Login | Nozomi Networks Console"',
    'http.title:"PMM Installation Wizard"',
    'http.title:"posthog"',
    'http.title:"PowerCom Network Manager"',
    'http.title:"Powered By Jetty"',
    'http.title:"Powered by lighttpd"',
    'http.title:"PowerJob"',
    'http.title:"prime infrastructure"',
    'http.title:"Puppetboard"',
    'http.title:"Ranger - Sign In"',
    'http.title:"rconfig"',
    'http.title:"RD Web Access"',
    'http.title:"Remkon Device Manager"',
    'http.title:"Reolink"',
    'http.title:"rocket.chat"',
    'http.title:"RouterOS router configuration page"',
    'http.title:"roxy file manager"',
    'http.title:"R-SeeNet"',
    'http.title:"seagate nas - seagate"',
    'http.title:"SearXNG"',
    'http.title:"Secure Login Service"',
    'http.title:"securepoint utm"',
    'http.title:"SeedDMS"',
    'http.title:"Selenium Grid"',
    'http.title:"Self Enrollment"',
    'http.title:"SequoiaDB"',
    'http.title:"Server Backup Manager SE"',
    'http.title:"SevOne NMS - Network Manager"',
    'http.title:"S-Filer"',
    'http.title:"SGP"',
    'http.title:"SHOUTcast Server"',
    'http.title:"sidekiq"',
    'http.title:"Sign In - Hyperic"',
    'http.title:"Sign in to Netsparker Enterprise"',
    'http.title:"SimpleSAMLphp installation page"',
    'http.title:"Skeepers"',
    'http.title:"SMS Gateway | Installation"',
    'http.title:"smtp2go"',
    'http.title:"Snapdrop"',
    'http.title:"SoftEther VPN Server"',
    'http.title:"SOGo"',
    'http.title:"Sonatype Nexus Repository"',
    'http.title:"Splunk"',
    'http.title:"Splunk SOAR"',
    'http.title:"SQL Buddy"',
    'http.title:"SteVe - Steckdosenverwaltung"',
    'http.title:"storybook"',
    'http.title:"Supermicro BMC Login"',
    'http.title:"swagger"',
    'http.title:"Symantec Encryption Server"',
    'http.title:"Synapse Mobility Login"',
    'http.title:"t24 sign in"',
    'http.title:"Tenda 11N Wireless Router Login Screen"',
    'http.title:"Test Page for the Apache HTTP Server on Red Hat Enterprise Linux"',
    'http.title:"Test Page for the HTTP Server on Fedora"',
    'http.title:"Test Page for the Nginx HTTP Server on Amazon Linux"',
    'http.title:"Test Page for the SSL/TLS-aware Apache Installation on Web Site"',
    'http.title:"The install worked successfully! Congratulations!"',
    'http.title:"thinfinity virtualui"',
    'http.title:"TileServer GL - Server for vector and raster maps with GL styles"',
    'http.title:"tixeo"',
    'http.title:"totolink"',
    'http.title:"traefik"',
    'http.title:"transact sign in","t24 sign in"',
    'http.title:"Transmission Web Interface"',
    'http.title:triconsole.com - php calendar date picker',
    'http.title:"TurnKey OpenVPN"',
    'http.title:"TYPO3 Exception"',
    'http.title:"UI for Apache Kafka"',
    'http.title:"UiPath Orchestrator"',
    'http.title:"UniFi Network"',
    'http.title:"UniGUI"',
    'http.title:"Verizon Router"',
    'http.title:"VERSA DIRECTOR Login"',
    'http.title:"ViewPoint System Status"',
    'http.title:"vRealize Operations Tenant App"',
    'http.title:"Wallix Access Manager"',
    'http.title:"Warning [refreshed every 30 sec.]"',
    'http.title:"Watershed LRS"',
    'http.title:"webcamXP 5"',
    'http.title:"webmin"',
    'http.title:"Web Server\'s Default Page"',
    'http.title:"WebSphere Liberty"',
    'http.title:"Webtools"',
    'http.title:"Web Transfer Client"',
    'http.title:"web viewer for samsung dvr"',
    'http.title:"Welcome to Citrix Hypervisor"',
    'http.title:"Welcome to CodeIgniter"',
    'http.title:"Welcome to nginx!"',
    'http.title:"welcome to ntop"',
    'http.title:"Welcome to OpenResty!"',
    'http.title:"Welcome To RunCloud"',
    'http.title:"Welcome to Service Assistant"',
    'http.title:"Welcome to Sitecore"',
    'http.title:"Welcome to Symfony"',
    'http.title:"Welcome to tengine"',
    'http.title:"Welcome to VMware Site Recovery Manager"',
    'http.title:"Welcome to your Strapi app"',
    'http.title:"Wi-Fi APP Login"',
    'http.title:"Wiren Board Web UI"',
    'http.title:"WoodWing Studio Server"',
    'http.title:"XAMPP"',
    'http.title:"XDS-AMR - status"',
    'http.title:"XenForo"',
    'http.title:"XNAT"',
    'http.title:"YApi"',
    'http.title:zblog',
    'http.title:"zentao"',
    'http.title:"zeroshell"',
    'http.title:"Zope QuickStart"',
    'http.title:"zywall"',
    'http.title:"ZyWall"',
    'http.title:"小米路由器"',
    'http.title:"高清智能录播系统"',
    'icon_hash="915499123"',
    '"If you find a bug in this Lighttpd package, or in Lighttpd itself"',
    'imap',
    'Laravel-Framework',
    'ldap',
    '"Lorex"',
    '"loytec"',
    '"Max-Forwards:"',
    'Microsoft FTP Service',
    'mongodb server information',
    '"Ms-Author-Via: DAV"',
    'MSMQ',
    '"nimplant C2 server"',
    '"OfficeWeb365"',
    'ollama',
    '"Ollama is running"',
    'OpenSSL',
    '"Open X Server:"',
    'Path=/gespage',
    'pentaho',
    'php.ini',
    '"PHPnow works"',
    '".phpunit.result.cache"',
    'pop3 port:110',
    'port:10001',
    '"port:110"',
    'port:"111"',
    'port:11300 "cmd-peek"',
    'port:1433',
    'port:22',
    'port:2375 product:"docker"',
    'port:23 telnet',
    '"port:3306"',
    'port:3310 product:"ClamAV"',
    'port:3310 product:"ClamAV" version:"0.99.2"',
    '"port:445"',
    'port:445',
    'port:523',
    'port:5432',
    'port:5432 product:"PostgreSQL"',
    '"port:69"',
    'port:"79" action',
    'port:"873"',
    'port:873',
    'product:"ActiveMQ OpenWire transport"',
    'product:"Apache ActiveMQ"',
    'product:"Ares RAT C2"',
    'product:"Axigen"',
    'product:"besu"',
    'product:"BGP"',
    'product:"bitvise"',
    'product:"Check Point Firewall"',
    'product:"Cisco fingerd"',
    'product:"cloudflare-nginx"',
    'product:"CouchDB"',
    'product:"DarkComet Trojan"',
    'product:"DarkTrack RAT Trojan"',
    'product:"Dropbear sshd"',
    'product:"Erigon"',
    'product:"Erlang Port Mapper Daemon"',
    'product:"etcd"',
    'product:"Exim smtpd"',
    'product:"Geth"',
    'product:"GitLab Self-Managed"',
    'product:"GNU Inetutils FTPd"',
    'product:"HttpFileServer httpd"',
    'product:"IBM DB2 Database Server"',
    'product:"Kafka"',
    'product:"kubernetes"',
    'product:"Kubernetes" version:"1.21.5-eks-bc4871b"',
    'product:"Linksys E2000 WAP http config"',
    'product:"MikroTik router ftpd"',
    'product:"MikroTik RouterOS API Service"',
    'product:"Minecraft"',
    'product:"MS .NET Remoting httpd"',
    'product:"mysql"',
    'product:"MySQL"',
    'product:"Nethermind"',
    'product:"Niagara Fox"',
    'product:"nPerf"',
    'product:OpenEthereum',
    'product:"OpenResty"',
    'product:"OpenSSH"',
    'product:"Oracle TNS Listener"',
    'product:"Oracle Weblogic"',
    'product:"Orcus RAT Trojan"',
    'product:"PostgreSQL"',
    'product:"ProFTPD"',
    'product:"RabbitMQ"',
    'product:"rhinosoft serv-u httpd"',
    'product:"Riak"',
    'product:"Sliver C2"',
    'product:"TeamSpeak 3 ServerQuery"',
    'product:"VMware Authentication Daemon"',
    'product:"vsftpd"',
    'product:"Xlight ftpd"',
    'product:"XtremeRAT Trojan"',
    '"python/3.10 aiohttp/3.8.3" && bad status',
    'realm="karaf"',
    '"RTM WEB"',
    '"RT-N16"',
    'RTSP/1.0',
    'secmail',
    '"SEH HTTP Server"',
    '"Server: Boa/"',
    '"Server: Burp Collaborator"',
    '"Server: EC2ws"',
    '"Server: ecstatic"',
    '"Server: Flowmon"',
    '"Server: gabia"',
    '"Server: GeoHttpServer"',
    '"Server: Goliath"',
    '"Server: httpd/2.0 port:8080"',
    '"Server: mikrotik httpproxy"',
    '"Server: Mongoose"',
    '"Server: tinyproxy"',
    '"Server: Trellix"',
    '"Set-Cookie: MFPSESSIONID="',
    '"set-cookie: nsbase_session"',
    'sickbeard',
    'smtp',
    'SSH-2.0-AWS_SFTP_1.1',
    '"SSH-2.0-MOVEit"',
    'SSH-2.0-ROSSSH',
    'ssl:"AsyncRAT Server"',
    'ssl.cert.issuer.cn:"QNAP NAS",title:"QNAP Turbo NAS"',
    'ssl.cert.serial:146473198',
    'ssl.cert.subject.cn:"Quasar Server CA"',
    'ssl:"Covenant" http.component:"Blazor"',
    'ssl.jarm:07d14d16d21d21d07c42d41d00041d24a458a375eef0c576d23a7bab9a9fb1+port:443',
    'ssl:"Kubernetes Ingress Controller Fake Certificate"',
    'ssl:"MetasploitSelfSignedCA"',
    'ssl:"Mythic"',
    'ssl:Mythic port:7443',
    'ssl:"P18055077"',
    'ssl:postalCode=3540 ssl.jarm:3fd21b20d00000021c43d21b21b43de0a012c76cf078b8d06f4620c2286f5e',
    'ssl.version:sslv2 ssl.version:sslv3 ssl.version:tlsv1 ssl.version:tlsv1.1',
    '"Statamic"',
    '".styleci.yml"',
    '"The requested resource"',
    '"TIBCO Spotfire Server"',
    'title:"3ware"',
    'title:"Acunetix"',
    'title:"AddOnFinancePortal"',
    'title:"Administration login" html:"poste"',
]

def search_shodan(query):
    try:
        results = api.search(query)
        return results
    except shodan.APIError as e:
        print(f"Erro ao consultar {query}: {e}")
        return None

def send_telegram_message(message):
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    data = {
        'chat_id': TELEGRAM_CHAT_ID,
        'text': message,
        'parse_mode': 'Markdown'
    }
    response = requests.post(url, data=data)
    if response.status_code != 200:
        print(f"Erro ao enviar mensagem para o Telegram: {response.text}")
    else:
        print("Mensagem enviada com sucesso!")

def main(host):
    
    dorks_selecionadas = random.sample(dorks, 20)

    resultados = []

    for dork in dorks_selecionadas:
        query = f"{dork} {host}"  # Combina a dork com o host
        print(f"Pesquisando: {query}")
        results = search_shodan(query)
        if results and results['matches']:
            for match in results['matches']:
                ip_str = match.get('ip_str', 'IP não disponível')
                org = match.get('org', 'Organização não disponível')
                data_str = f"*Dork:* {dork}\n*Host:* {host}\n*IP:* {ip_str}\n*Organização:* {org}\n"
                resultados.append(data_str)
        else:
            print(f"Nenhum resultado encontrado para {query}.")

    # Enviar resultados em blocos de até 4096 caracteres para o Telegram
    mensagem = ""
    for resultado in resultados:
        if len(mensagem) + len(resultado) > 4096:
            send_telegram_message(mensagem)
            mensagem = ""
        mensagem += resultado

    if mensagem:
        send_telegram_message(mensagem)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Script para buscar dorks no Shodan e enviar resultados para o Telegram")
    parser.add_argument('host', help="Host (IP ou domínio) para buscar no Shodan")
    args = parser.parse_args()
    main(args.host)